# Generated by Django 2.1.8 on 2019-04-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('star', models.DecimalField(decimal_places=2, max_digits=5)),
                ('singer', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('classification', models.CharField(max_length=255)),
            ],
        ),
    ]
